# Generated by Django 6.0.6 on 2026-06-21 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('timeout', models.PositiveIntegerField()),
                ('alert_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('down', 'Down')], default='active', max_length=20)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
