# Generated by Django 6.0.6 on 2026-06-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertLog',
        ),
    ]
